language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer self-update
  - composer install --dev --no-interaction --prefer-source

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate --phpbb-version="3.1" --package-dir="phpBB/language" --language-dir="phpBB/language" pl

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
