language: php

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

install:
  - composer install --dev --no-interaction --prefer-source
  - git clone git://github.com/phpbb/phpbb-app.git --branch=develop-ascraeus --depth=1

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate --phpbb-version="3.1" --package-dir="phpBB/language" --language-dir="phpbb-app/language" pl

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
