language: php
sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

install:
  - composer install --dev --no-interaction --prefer-source
  - git clone git://github.com/phpbb/phpbb.git --branch=release-3.1.9 --depth=1
  - cp -R phpbb/phpBB/language/en/ phpBB/language/en/

script:
  - php vendor/bin/PhpbbTranslationValidator.php validate --phpbb-version="3.1" --language-dir="phpBB/language" pl

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
